invoicing/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    #Examples:
    #url(r'^$', 'invoicing.views.home', name='home'),
    #url(r'^blog/', include('blog.urls')),
	
	url(r'^$', 'invoice_app.views.index', name='index'),
	url(r'^customerlist/', 'invoice_app.views.customer_list', name='customer_list'),
	url(r'^createinvoice/', 'invoice_app.views.create_invoice', name='create_invoice'),
	url(r'^addcustomer/', 'invoice_app.views.add_customer', name='add_customer'),
    url(r'^admin/', include(admin.site.urls)),
)

invoice_app/models/customer.py
from django.db import models


class Customer(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	work_phone = models.CharField(max_length=10, null=True, blank=True)
	home_phone = models.CharField(max_length=10, null=True, blank=True)
	email = models.EmailField(max_length=254)
	created_date = models.DateField(auto_now_add=True)
	is_archived = models.BooleanField(default=False)
	
	def __str__(self):
		return self.first_name + " " + self.last_name
	
	
class Address(models.Model):
	address1 = models.CharField(max_length=200)
	address2 = models.CharField(max_length=200, blank=True, null=True)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=2)
	zip = models.IntegerField()
	customer = models.ForeignKey(Customer)
	
	def __str__(self):
		return self.address1 + " " + self.city + ", " + self.state + " " + str(self.zip)
				

invoice_app/views.py
from django.shortcuts import render
from models.customer import Customer, Address
from django.forms import ModelForm
from django import forms
from django.http import HttpResponseRedirect
from django.contrib import messages


class AddCustomerForm(ModelForm):
	address1 = forms.CharField(max_length=50)
	address2 = forms.CharField(max_length=50,required=False)
	city = forms.CharField(max_length=40)
	state = forms.CharField(max_length=2)
	zip = forms.IntegerField()
	
	class Meta:
		model = Customer
		fields = ('first_name',
				  'last_name',
				  'home_phone',
				  'work_phone',
				  'email',
				  )
		

def index(request):
	return render(request, 'index.html', {})

def add_customer(request):
	if request.method == 'POST':
		form = AddCustomerForm(request.POST)
		if form.is_valid():
			messages.success(request, "New Customer added successfully")
			# save the Customer model info
			new_customer = form.save()
			# get the Customer object that we just created
			new_customer = Customer.objects.latest('id')
			# create a new address and tie it to that new Customer
			Address.objects.create(
				address1 = form.cleaned_data['address1'],
				address2 = form.cleaned_data['address2'],
				city = form.cleaned_data['city'],
				state = form.cleaned_data['state'],
				zip = form.cleaned_data['zip'],
				customer = new_customer
			)
			return HttpResponseRedirect('/addcustomer/')
	elif request.method == 'GET':
		form = AddCustomerForm()
	else:
		return HttpResponseRedirect('/addcustomer/')
	return render(request, 'add_customer.html', {'form': form})
			
def customer_list(request):
	customers = Customer.objects.all()
	return render(request, 'customer_list.html', { 'customers': customers })
	
def create_invoice(request):
	pass
	

templates/invoice_app/_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styling -->
    <link href="/static/css/all_pages.css" rel="stylesheet">

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	    <!-- Fixed navbar -->
	    <nav class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="{% url 'index' %}">RaM0</a>
	        </div>
	        <div id="navbar" class="navbar-collapse collapse">
	          <ul class="nav navbar-nav">
	            <li class="active"><a href="{% url 'index' %}">Home</a></li>
	            <li><a href="{% url 'customer_list' %}">List Customers</a></li>
	            <li><a href="{% url 'add_customer' %}">Add Customer</a></li>
	            <li class="dropdown">
	              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Invoicing<span class="caret"></span></a>
	              <ul class="dropdown-menu" role="menu">
	                <li><a href="#">Some action</a></li>
	                <li><a href="#">Another action</a></li>
	                <li><a href="#">Something else here</a></li>
	                <li class="divider"></li>
	                <li class="dropdown-header">Nav header</li>
	                <li><a href="#">Separated link</a></li>
	                <li><a href="#">One more separated link</a></li>
	              </ul>
	            </li>
	          </ul>
	        </div><!--/.nav-collapse -->
	      </div>
	    </nav>
		{% block head %}{% endblock %}
	  </head>
	  <body>
  	<div class="container">
    {% block content %}{% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

templates/invoice_app/add_customer.html
{% extends '_base.html' %}
{% load staticfiles %}
{% block head %}
	<title>Add Customer</title>
	<link rel="stylesheet" href="/static/css/forms.css">
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
	<h1>Add Customer</h1>
	{% if messages %}
	  <div class="alert alert-success" role="alert">
		{% for message in messages %}
			{{ message }}
		{% endfor %}
	  </div>
	{% endif %}
	<form class="form-horizontal" action="{% url 'add_customer' %}" method='post'>
		<div class="form-group">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-default btn-lg" type='submit'>Add</button>
		</div>
	</form>
	</div>
    <div class="col-md-3"></div>
  </div>
</div>
{% endblock %}

templates/invoice_app/customer_list.html
{% extends '_base.html' %}
{% block content %}
<div class="container">
  <div class="row">
	<div class="col-md-2"></div>
	<div class="col-md-8">
	<h1>Customer List</h1>
	{% for customer in customers %}
		{% if not customer.is_archived %}
		<div class='well'>
			<h2>Name: {{ customer }}</h2>
			<p>phone: {{ customer.home_phone }}</p>
			<h4>Addresses:</h4>
			<ul>
			{% for address in customer.address_set.all %}
				<li>{{ address }}</li>
			{% endfor %}
			</ul>
		</div>
		{% endif %}
	{% endfor %}
	</div>
    <div class="col-md-2"></div>
  </div>
</div>
{% endblock %}

templates/invoice_app/index.html
{% extends '_base.html' %}
{% block content %}
	<h1>Invoicing System</h1>
	<ul>
		<li><a href="{% url 'customer_list' %}">Customer List</a></li>
		<li><a href="{% url 'add_customer' %}">Add Customer</a></li>
		<li><a href="{% url 'create_invoice' %}">Create Invoice</a></li>
	</ul>
{% endblock %}